// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHJ7dF6t7hcgr7wUFGrTIMdxCFt1Nobs',
    appId: '1:859622971414:web:7ba5e921d7fd611358bd37',
    messagingSenderId: '859622971414',
    projectId: 'my-app-946fc',
    authDomain: 'my-app-946fc.firebaseapp.com',
    storageBucket: 'my-app-946fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsSBkDSylnUKC1NuULTxS-HRRTt7N0Fg0',
    appId: '1:859622971414:android:a9c0cfde2b7bf0be58bd37',
    messagingSenderId: '859622971414',
    projectId: 'my-app-946fc',
    storageBucket: 'my-app-946fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_7N36GiJ_0xxhkdItAP0sOVzO4sN4EGA',
    appId: '1:859622971414:ios:eba55ca6f781929558bd37',
    messagingSenderId: '859622971414',
    projectId: 'my-app-946fc',
    storageBucket: 'my-app-946fc.appspot.com',
    iosClientId: '859622971414-ebv1hvh08giq202rj4ciqdqb79s6novg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
